### ISSUE TITLE
Could you create NEU Latex temples of thesis for Ph.D. or Master?

### ISSUE THREAD

**Issue by zhouyanasd** [tzaiyang/NEUBachelorThesis#1]
Finally, I found someone wants to create latex temple for NEU. If you could create Latex temple for Ph.D. or Master, it would be very appreciated!

**Comment by tzaiyang** [comment]
@zhouyanasd ,Thanks for your attention,I will take your proposal into consideration.

Expect your continuous attention.

**Comment by zhouyanasd** [comment]
Thank you for your reply, I will keep this proposal up and thank you once again.
